name: build
on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: install packages/core
        uses: borales/actions-yarn@v4
        with:
          dir: packages/core
          cmd: install # will run `yarn install` command in packages/core
      - name: build packages/core
        uses: borales/actions-yarn@v4
        with:
          dir: packages/core
          cmd: build # will run `yarn build` command in packages/core
      - name: link packages/core
        uses: borales/actions-yarn@v4
        with:
          dir: packages/core
          cmd: link # will run `yarn link` command to make packages/core package the package used in packages/mirrorful
      - name: install packages/mirrorful
        uses: borales/actions-yarn@v4
        with:
          dir: packages/mirrorful
          cmd: install # will run `yarn install` command in packages/mirrorful
      - name: build packages/mirrorful
        uses: borales/actions-yarn@v4
        with:
          dir: packages/mirrorful
          cmd: build # will run `yarn build` command in packages/mirrorful
